webtalk_init -webtalk_dir C:/Users/Juanma/Documents/CESE/CLP/TPs_CLP/TP_Final/FIR_Filter_VIO/Sintesis/FIR_Filter_VIO.sim/sim_1/behav/xsim/xsim.dir/FIR_Filter_VIO_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 15 22:42:37 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "99308b43-13e3-438a-bf18-5112d3a18bec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0b3c94f25520402fac241dd2fea2824c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-1235U" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "71 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "8" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.41_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "11268_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2929899253 -regid "" -xml C:/Users/Juanma/Documents/CESE/CLP/TPs_CLP/TP_Final/FIR_Filter_VIO/Sintesis/FIR_Filter_VIO.sim/sim_1/behav/xsim/xsim.dir/FIR_Filter_VIO_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Juanma/Documents/CESE/CLP/TPs_CLP/TP_Final/FIR_Filter_VIO/Sintesis/FIR_Filter_VIO.sim/sim_1/behav/xsim/xsim.dir/FIR_Filter_VIO_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Juanma/Documents/CESE/CLP/TPs_CLP/TP_Final/FIR_Filter_VIO/Sintesis/FIR_Filter_VIO.sim/sim_1/behav/xsim/xsim.dir/FIR_Filter_VIO_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
